version: "3.3"
services:
  web:
    image: hashicorp/http-echo
    command: -text="hello world, from web"
  web2:
    image: hashicorp/http-echo
    command: -text="hello world, from web 2"
  web3:
    image: hashicorp/http-echo
    command: -text="hello world, from web 3"

  rtunnel:
    build: .
    volumes:
      - rtunnel:/root/.ssh
    environment:
      - TARGET=user@my-remote-host
      - TARGET_PORT=22
      - R_TUNNEL_0=3000:web:5678
      - R_TUNNEL_1=3001:web2:5678
      - R_TUNNEL_2=3002:web3:5678

  ltunnel:
    volumes:
      - rtunnel:/root/.ssh
      - TARGET=user@my-jump-host
      - TARGET_PORT=22
      - L_TUNNEL_0=3306:my-sql-host:3306
      - SSH_OPTS=-v
    ports:
      - 3306:3306

volumes:
  rtunnel:
