version: "3.3"
services:
  web:
    image: hashicorp/http-echo
    command: -text="hello world, from web"
  web2:
    image: hashicorp/http-echo
    command: -text="hello world, from web 2"
  web3:
    image: hashicorp/http-echo
    command: -text="hello world, from web 3"
  rtunnel:
    build: .
    volumes:
      - rtunnel:/root/.ssh
    environment:
      - RT_TARGET=user@myhost
      - RT_TARGET_PORT=22
      - RT_TUNNEL_0=3000:web:5678
      - RT_TUNNEL_1=3001:web2:5678
      - RT_TUNNEL_2=3002:web3:5678
      # - SSH_OPTS=-v
volumes:
  rtunnel:
